Download churn modelling dataset from the kaggle 

You will be solving a data analytics challenge for a bank.You will be given dataset with large sample of banks customers. To make this dataset, the bank gathered info such as customer id, credit score, gender, age, tenue, balance, if the customer is active, has a credit card, etc. During 6 months, the bank observed if these customer left or stayed in bank.

#                          Part ( A )

### 1. Data Preprocessing
### Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 2. Load Dataset

In [2]:
dataset=pd.read_csv("data/Churn_Modelling.csv")
#  View Dataset
print(dataset.head(2))
print(dataset.columns)

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')


### 3. Check for important columns which affect our analysis

In [3]:
# saperate dependent and independent value
X= dataset.iloc[:,3:13].values  # first val include and last not include so use 13 , i.e we can get 12 no. values
y= dataset.iloc[:,13].values

### 4. Encoding of Categorical data
        In our dataset Geography and Gender attribute is in text format and we enocode these two attribute in this part by using LabelEncoder and OneHotEncoder from sklearn.preprocessing library

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X1= LabelEncoder()
labelencoder_X1.fit_transform(X[:,1])

labelencoder_X2= LabelEncoder()
labelencoder_X2.fit_transform(X[:,2])

# identify indices or name of categorical col
categorical_cols= [1,2] # replace with col indices

#create columnTransformer
ct= ColumnTransformer(transformers=[ ('encoder', OneHotEncoder(), categorical_cols )],
                      remainder= 'passthrough') #keep all other col as they are )

# apply it to your dataset
X= ct.fit_transform(X)

#onehotencoder= OneHotEncoder(categorical_feature = [1])
# X = onehotencoder.fit_transorm(X).toarry()
X= X[:,1:]
X

array([[0.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [0.0, 1.0, 1.0, ..., 0, 1, 112542.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 92888.52],
       [0.0, 0.0, 1.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

### 5. Split data for Train (80%), Test(20)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2, random_state=0)

### 6. Feature Scalling
        It is most important part of data preprocessing. our datset, some attribute contains info in num val, some very high and some very low. If we see age, estimated salary. this will cause some issue in machinery model to solve that problem we set all val on same scale there ae two methods to solve this issue. 1. Normalization 2. Standard Scaler

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test=sc.transform(X_test)
            

#  Part ( B )

## 1. Building our model - ANN  model
###  we import lib which will build our ANN model - keras which build deep Neural network based on tesnsorflow, because we use tensorflow backhand. Here we import two module from kers
 ### i. sequential use for initilizing our ANN model
 ### ii. dense use for adding different layer of ANN

In [7]:
import tensorflow.keras
# from sklearn.models import sequential
# from sklearn.layers import Dense

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [8]:
# initilize our ANN model using sequential model
classifier = Sequential()

In [9]:
# add input layer and first hidden layer 
classifier.add(Dense(units=1,activation='relu'))
classifier.add(Dense(1,activation='relu'))

## 2. Fitting ANN

In [10]:
# # 1. Check data shapes
# print("--- Data Shapes ---")
# print(f"X_train shape: {X_train.shape} | Data type: {type(X_train)}")
# print(f"y_train shape: {y_train.shape} | Data type: {type(y_train)}")

# # 2. Check model structure
# print("\n--- Model Architecture ---")
# classifier.summary()


In [11]:
# import tensorflow as  tf
# classifier = tf.keras.Sequential([
#     # Notice the comma: (12,) means 12 features, any batch size
#     tf.keras.layers.Dense(units=6, activation='relu', input_shape=(12,)), 
#     tf.keras.layers.Dense(units=6, activation='relu'),
#     tf.keras.layers.Dense(units=1, activation='sigmoid')
# ])



## 3. Compile ANN


In [12]:
#classifier.compile(optimizer='adam',loss='binary-entropy', metrics=['accuracy'])

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [13]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6440 - loss: 4.5698
Epoch 2/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6450 - loss: 4.5428
Epoch 3/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6466 - loss: 4.5196
Epoch 4/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6513 - loss: 4.4311
Epoch 5/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6534 - loss: 4.4169
Epoch 6/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6550 - loss: 4.3980
Epoch 7/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6580 - loss: 4.3516
Epoch 8/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6646 - loss: 4.2458
Epoch 9/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6755 - loss: 4.0312
Epoch 10/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6954 - loss: 3.7521
Epoch 11/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7178 - loss: 3.2958
Epoch 12/100
800/800 ━━━━━━━━━━━━━━━━━━━━

# PART (C)
### Make Prediction and accuracy result

In [14]:
# predict test set result
y_pred=classifier.predict(X_test)
y_pred=(y_pred > 0.5)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]], shape=(2000, 1))

## 2. Confusion metrics
###     make CM for our test result set . y_test ( actual result) , y_pred(predicted result)

In [15]:

from sklearn.metrics import confusion_matrix
confusion_matrix= confusion_matrix(y_test, y_pred)
confusion_matrix

array([[1546,   49],
       [ 334,   71]])

## 3. accuracy score


In [17]:

from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test,y_pred)
accuracy

0.8085